language: ruby
rvm:
  - 2.2
bundler_args: --without development --deployment
cache: bundler
before_script:
  - wget http://download.processing.org/processing-3.1.1-linux64.tgz
  - tar xvfz processing-3.1.1-linux64.tgz
  - export PATH=./processing-3.1.1:$PATH
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rspec spec
services:
  - mysql
  - redis-server
addons:
  code_climate:
    repo_token: 7d22b64cc7d79e88a6ddd0b1696bee4a4fb5556cc9d9b1f16d3050571562a1a0
