version: '2'
services:
  rails:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/poj
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    environment:
      DATABASE_URL: mysql2://root:root@mysql:3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  redis:
    image: redis
