version: '2'
services:
  rails:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/poj
      - /poj/processing-3.1.1
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  redis:
    image: redis
  sidekiq:
    command: bundle exec sidekiq
    build: .
    links:
      - redis
      - mysql
